xp11:
    lat: '__lat,__deg'
    lon: '__lon,__deg'
    alt: '__alt,ftmsl'
    hgt: '__alt,ftagl'
    hdg: 'hding,__mag'
    ias: '_Vind,_kias'
    tas: 'Vtrue,_ktas'
    gs: 'Vtrue,_ktgs'
    vs: '__VVI,__fpm'
    rwy: '___on,runwy'
    om: '___OM,morse'
    mm: '___MM,morse'
    im: '___IM,morse'
    flp: '_flap,postn'
    stl: 'stall,_warn'
    time: '_real,_time'
